spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379

server:
  host: http://localhost
  port: 8080

logging:
  level:
    root: info
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN
    org.hibernate.SQL: WARN

url:
  shortener:
    hash:
      batch-size: 2000
    cache:
      refill-threshold: 90
      capacity: 20000
  validation:
    allowed-protocols: http,https
    max-length: 2048

  cleaner:
    cron: 0 0 0 * * *
    batch-size: 100